### ISSUE TITLE
couldn't install composer

### ISSUE THREAD

**Issue by thanhtutoo** [christophrumpel/chatbot-php-boilerplate#1]
when i run composer install in terminal
it show Your requirements could not be resolved to an installable set of packages.

Problem 1
    - Installation request for phpunit/php-code-coverage 4.0.1 -> satisfiable by phpunit/php-code-coverage[4.0.1].
    - phpunit/php-code-coverage 4.0.1 requires php ^5.6 || ^7.0 -> your PHP version (5.5.31) does not satisfy that requirement.
  Problem 2
    - Installation request for phpunit/phpunit 5.5.0 -> satisfiable by phpunit/phpunit[5.5.0].
    - phpunit/phpunit 5.5.0 requires php ^5.6 || ^7.0 -> your PHP version (5.5.31) does not satisfy that requirement.
  Problem 3
    - Installation request for phpunit/phpunit-mock-objects 3.2.3 -> satisfiable by phpunit/phpunit-mock-objects[3.2.3].
    - phpunit/phpunit-mock-objects 3.2.3 requires php ^5.6 || ^7.0 -> your PHP version (5.5.31) does not satisfy that requirement.
  Problem 4
    - Installation request for sebastian/code-unit-reverse-lookup 1.0.0 -> satisfiable by sebastian/code-unit-reverse-lookup[1.0.0].
    - sebastian/code-unit-reverse-lookup 1.0.0 requires php >=5.6 -> your PHP version (5.5.31) does not satisfy that requirement.
  Problem 5
    - Installation request for sebastian/object-enumerator 1.0.0 -> satisfiable by sebastian/object-enumerator[1.0.0].
    - sebastian/object-enumerator 1.0.0 requires php >=5.6 -> your PHP version (5.5.31) does not satisfy that requirement.
  Problem 6
    - Installation request for sebastian/resource-operations 1.0.0 -> satisfiable by sebastian/resource-operations[1.0.0].
    - sebastian/resource-operations 1.0.0 requires php >=5.6.0 -> your PHP version (5.5.31) does not satisfy that requirement.
  Problem 7
    - Installation request for sebastian/version 2.0.0 -> satisfiable by sebastian/version[2.0.0].
    - sebastian/version 2.0.0 requires php >=5.6 -> your PHP version (5.5.31) does not satisfy that requirement.

**Comment by christophrumpel** [comment]
Do you run the latest composer version?

**Comment by thanhtutoo** [comment]
I am sorry,my php version was 5.5.3,didnt notice ur requirement php 7,
thank you so much,now I could do it.

**Comment by thanhtutoo** [comment]
Bro,can u implementing for the witAI answering,?? 
if you have time,please answer me bro.
Thank you so much

**Comment by christophrumpel** [comment]
I will add an example in the next days.

**Comment by thanhtutoo** [comment]
wow,I really thank you bro,waiting for that.
Thank you so much again!

**Comment by christophrumpel** [comment]
Hey, sry didnt had enough time. Today I pushed a new commit with basic wit.ai logic, but I hadn't time to document it. Will do that the next days, but you can already look into the code if you like.

**Comment by christophrumpel** [comment]
Hey @thanhtutoo , now a simple Wit.ai example is included in this repo and readme. Check it out.
