### ISSUE TITLE
Dialogflow Intent with multiple parameters / prompts

### ISSUE THREAD

**Issue by gdpsysgarage** [christophrumpel/chatbot-php-boilerplate#14]
Hi @christophrumpel !! 

I am developing a Facebook-Dialogflow chat bot with your code. 
I got it work but I have one problem. 

I created an Dialogflow intenet with multiple parameters. 
Every parameter has, at least, one prompt question to get it value.
The problem, is that when this intent is reached, only the first "Prompt" question is showing and after answering it, the "Default Fallback" intent is triggering. 
It seems like the chatbot doesnt follow the parameters flow of the intent.

**Comment by gdpsysgarage** [comment]
can u help me @christophrumpel  ?

**Comment by christophrumpel** [comment]
Sry I forgot to come back here. Ok I see where this is going. I would recommend using [BotMan](https://botman.io). Have checked that already? It is a great PHP framework for chatbots and provides much more features like my boilerplate. This boilerplate is just for experimenting and to make yourself familiar with chatbots. I could some more features, but then it gets difficult where to stop.

**Comment by gdpsysgarage** [comment]
Hi @christophrumpel  !! 

Yes I tried Botman and this issue doesnt happend there. 
But it appears others that I'm waiting for some help.

**Comment by christophrumpel** [comment]
Hey, sorry I didn't get that. It works in BotMan but you don't want to use it? Or do you got there another problem where you need help? Or do you want to make it work with my boilerplate?

**Comment by gdpsysgarage** [comment]
Hi @christophrumpel  !! 
This one --> Or do you got there another problem where you need help? 

I have tried Botman. This issue didnt appear using it, but now I got an other problem. 
I dont know if you have some  influence there, but here is the link of my new issue 
https://github.com/botman/botman/issues/769

Thanks !!

**Comment by christophrumpel** [comment]
Ah I see. Marcel is right now very busy, this is why he hasn't responded yet. I can try to look into this problem this week, but I'm busy as well. I would also try coming to the BotMan Slack team https://slack.botman.io/.

**Comment by gdpsysgarage** [comment]
@christophrumpel thanks !! 
If you can help me I will be very grateful cause I have stopped my development  for this

**Comment by poojanetsol** [comment]
Hello , Can somebody help me with how to call multiple intents of dialog flow and how we can call in conversation of botman
