### ISSUE TITLE
Get Wit.AI Story Bot Answer

### ISSUE THREAD

**Issue by TobiM93** [christophrumpel/chatbot-php-boilerplate#3]
First of all, thank you very much for this awesome Repo.
I already tried the GetAnswer() function and I get the right intent. 
Is there any way how I can get the Bot answers from my story?

**Comment by christophrumpel** [comment]
I'll try to take a look tonight.

**Comment by TobiM93** [comment]
Hi thank you very much. I'll also try to find a solution, should work via the /converse Request from Wit.ai. I already worked with the https://github.com/tgallice/wit-php repo but don't understand the /converse Request with the Session_ID part.

**Comment by TobiM93** [comment]
Hi @christophrumpel just tried the following solution and hope you can propably work with this. Would be awesome if it could be applied to the Boilerplate, if you create the Session ID and call the CURL Request it echos the messages which you defined in your story inside wit.

```
<?php
                                                                                  
$ch = curl_init();
$Input="TEXT";
$Input=urlencode($Input);
curl_setopt($ch, CURLOPT_URL,"https://api.wit.ai/converse?v=20160526&session_id=SESSIONID&q=$Input");
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS,$vars);  //Post Fields
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

$headers = [
  	'Content-Type: application/json', 
    'Authorization: Bearer TOKEN',
    'Accept: application/json'
];

curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$server_output = curl_exec ($ch);

curl_close ($ch);

$output=json_decode($server_output, true);
echo $output["msg"];
?>
```

**Comment by christophrumpel** [comment]
Thx @TobiM93 , unfortunately I did not had the time to take care of it. I will let you know.

**Comment by christophrumpel** [comment]
So I just took a look. I am using the wit-api right now too and you're right the converse example is not that easy. They are using a separate class for the conversation mapping because the answer could be a msg or an action etc. This does not work like this in my boilerplate because I want to return the msg immediately.

I also checkout your code and it is working. But after the first right response I get a "stop" type backe, because with the same session_id there is no more reply. (in my wit story there is just a hello and hello back)

So I am not sure how to implement that without overwhelming users. This boilerplate should just be a first start into playing with a chatbot. I am not sure if there is place for the wit.ai stories here. What do you think @TobiM93 . What are you using it for?

**Comment by TobiM93** [comment]
Hi @christophrumpel I'm sorry for the late reply. Well you're right, basically I thought that it's much more easier to use a wit story than to code a own "storyline". If you want to work with Wit.ai there currently two options: 

1. You use Wit.ai as an "interpreter" and use their technology to filter entities from messages and afterwards code your own actions and replies.  

2. You use the stories and directly reply to users in that way. 

Well for me the 2nd choice was quite tempting because if you do it in the right way you can build a working chatbot and connect it to almost every plattform without any bigger efforts. 

What's your opinion on api.ai and their system? I already checked out their interface but was not as satisfied as with the wit.ai one. I'm currently looking around for an solution to build chatbots with a minimum of efforts and waste of own ressources.

**Comment by christophrumpel** [comment]
Hey @TobiM93 , sry for the late reply. I missed your answer. I am a big fan of API.ai and I like it far more than Wit.ai. Better interface and nicer API.

I am working a lot with botman.io right now which is a multiple-channel chatbot library for PHP. It is not that easy to start but has lots of features.

I still want to keep this boilerplate as simple as possible to give people an easy entrance point to building a chatbot. I am sure there is place for improvements though.
