### ISSUE TITLE
No intent recognized

### ISSUE THREAD

**Issue by jwzk** [christophrumpel/chatbot-php-boilerplate#4]
Hi,

I config your repository and it's work !

But I want to link my bot with wit.ai, and when I send a message to my bot, I got "The intent of the message: no intent recognized".

Of course, I made a story in wit.ai, my bot work in wit.ai platform but only on messenge, bot answers "The intent of the message: no intent recognized"

Thank

**Comment by christophrumpel** [comment]
Hey @JulienWszolek , I will test it again.

**Comment by christophrumpel** [comment]
So I just tested it and it worked for me.

Have you set the `WITAI_TOKEN` in the `.env`file?

Can you try to log the response from Wit.ai. Add the line marked with `// this line` to the `Chatbot.AI.php` file. The output should then be in the `debug.log` file.

```php
try {

            $response = $this->witClient->get('/message', [
                'q' => $message,
            ]);

            // Get the decoded body
            $response = json_decode((string)$response->getBody(), true);
            $intent = $response['entities']['intent'][0]['value'] ?? 'no intent recognized';
            $this->log->info('Debug: ', $response); // this line
        } catch (\Exception $error) {
            $this->log->warning($error->getMessage());
        }

        return 'The intent of the message: ' . $intent;
    }
```

**Comment by thanhtutoo** [comment]
after added $this->log->info('Debug: ', $response);  
here is in debug.log

[2017-03-16 08:10:44] general.INFO: Debug:  {"msg_id":"67ac1514-f744-4beb-b6b9-ce412b93205b","_text":"hi","entities":{"intent":[{"confidence":0.92869822661728,"value":""}]}} []
[2017-03-16 08:10:46] general.INFO: Debug:  {"msg_id":"b3b8840a-fbc9-472f-9f59-cb5d86a79821","_text":"yo","entities":[]} []
[2017-03-16 08:10:50] general.INFO: Debug:  {"msg_id":"fdc76190-fc7d-494e-bb24-776043fbb5a6","_text":"yo","entities":[]} []



how can i fix it ,i am also facing the same problem above

like
The intent of the message: no intent recognized

help me bro
thanks.

**Comment by christophrumpel** [comment]
Hm  I would guess it has something todo with your wit.ai story. Can you show what you did there? Have you tried the wit.ai test console to see if you intent is matched there?

**Comment by thanhtutoo** [comment]
ahh, yeah its was wrong with my story, i didnt create intent.
Thanks, it fixed.
btw how can i get the bot ready made answer from story, now its only get the intent.

**Comment by christophrumpel** [comment]
Ok great 👍

Right now just the intent is used. I can change that. Maybe today or tomorrow. Will let you know.

**Comment by christophrumpel** [comment]
Hey @thanhtutoo , just looked into how to the text message. This is not that easy with Wit.ai and the  PHP client I am using. It's implementation would be beyond the goal to keep this chatbot entrance as simple as possible. This is why I won't implement that with Wit.ai.
