### ISSUE TITLE
Messenger webhook The URL couldn't be validated. Response does not match challenge,

### ISSUE THREAD

**Issue by marufmax** [christophrumpel/chatbot-php-boilerplate#5]
Thanks for this amazing package. 
 I have a simple issue when I am going to setup my webhook facebook gives me following error: 
 

The URL couldn't be validated. Response does not match challenge, expected value="1290381219", received="" 

Note that, I have correctly public my localhost URL via ngrok. 

Thank you

**Comment by christophrumpel** [comment]
Thx! Have you setup your `WEBHOOK_VERIFY_TOKEN`  in your `.env` file correctly and it is the same you use when you setup the webhook with FB?

**Comment by marufmax** [comment]
Yes, I have set up it. I don't know 

Here is the [screenshot ](http://prntscr.com/eltv65)

And here is the error message from web hook in messenger.  [screenshot](http://image.prntscr.com/image/908261d9b11447d3b17c7ef3bc1b78b2.png)

**Comment by christophrumpel** [comment]
Hey, you are using the wrong verify token. This is **not** the URL. It is a token that you can define. But it must be the same! (once in your .env file and the one you put into the field when you setup the FB webhook)

Do you know what I mean? Greets

**Comment by marufmax** [comment]
Thanks for reply but still no luck  :(  

Here is .env file [screenshot](http://prntscr.com/em59aw) and this is from [facebook ](http://prntscr.com/em59uc)

**Comment by christophrumpel** [comment]
Hmm ok that's correct. What happens if you visit the webhook URL in the browser? Do you get any errors or just blank site?

Depending on your local env you maybe need to add "index.php" to the end of the webhook URL. Please try that too.

**Comment by marufmax** [comment]
I am using Cloud9 IDE development environment. 

It gives me[ errors  ](http://prntscr.com/enfebd)

**Comment by christophrumpel** [comment]
Ah I see. This package need `PHP7+`. I guess you are using an older version right?

**Comment by marufmax** [comment]
No no, I am using [PHP 7 ](http://prntscr.com/enfs49)via I was installed it via phpbrew.  :(

**Comment by christophrumpel** [comment]
Are you sure? The errors seems like it is not 7. Can you check that with `phpinfo()` inside a file?

**Comment by oRouge911** [comment]
open file env 
change  "debug= true" to "debug=false"

**Comment by marufmax** [comment]
Sorry actually I was installed php 7 in CLI in phpinfo is still php5.3. 

Now I am successfully set up webhooks. Thank you very much.

**Comment by dinshawr** [comment]
I am facing given problem 

> The URL couldn't be validated. Response does not match challenge, expected value="182436379", received="Invalid verify token"

any solution for this https://github.com/netguru/messenger-ruby/issues/54

**Comment by ridleytech** [comment]
I was able to verify it by echo the verify token. See the attached screenshot

<img width="513" alt="screen shot 2017-12-26 at 10 42 36 am" src="https://user-images.githubusercontent.com/386803/34359906-cf9c2346-ea29-11e7-8b66-e2257fbdd456.png">

**Comment by princemoboni** [comment]
gh

**Comment by yhtag** [comment]
hey i got this error.please tell me how to solve :(
![image](https://user-images.githubusercontent.com/35452482/97927101-bee45d80-1d92-11eb-9280-3e1592d475d8.png)

**Comment by christophrumpel** [comment]
Please create a new issue with more details about your problem and your code.

**Comment by papnoisanjeev** [comment]
@yhtag 

Have you got any solution for this? getting the same error.
