### ISSUE TITLE
Symfony integration

### ISSUE THREAD

**Issue by grago** [christophrumpel/chatbot-php-boilerplate#6]
Hi, this is great stuff. 

I would like to integrate this library to my Symfony project. Do you have any recommendation on how to do it? I am relatively new to Symfony and i've never used a non-bundle external dependency.

Many thanks.

**Comment by christophrumpel** [comment]
Hey, sry for the late reply. I would not recommend using this library. It is just for testing and experimenting. Your production chatbots I would recommend botman.io. I can really recommend it for bigger and more complex projects.
