### ISSUE TITLE
setup my webhook facebook issue

### ISSUE THREAD

**Issue by SyedaNadia** [christophrumpel/chatbot-php-boilerplate#8]
I have a simple issue when I am going to setup my webhook Facebook gives me following error:

The URL couldn't be validated. Response does not match challenge, expected value="1909028616", received="Error, wrong token"

Note that, I have correctly used git and Heroku.

Thank you

**Comment by christophrumpel** [comment]
Hey, this means that the token verification did not work. Have you set the `WEBHOOK_VERIFY_TOKEN` in your `.env` file? and it is the same as in your FB app?
