### ISSUE TITLE
autoload file missing in vendor folder??

### ISSUE THREAD

**Issue by bambaaga** [christophrumpel/chatbot-php-boilerplate#9]
Hello,

I get this error:

[12-Aug-2017 12:45:37 UTC] PHP Warning:  require_once(/home/bambaaga/public_html/chatbot/vendor/autoload.php): failed to open stream: No such file or directory in /home/bambaaga/public_html/chatbot/index.php on line 3

Any idea where this vendor folder or autoload.php file will be?

Please let me know.

Thanks,
Bambaaga

**Comment by christophrumpel** [comment]
Hey @bambaaga , have you run "composer install" like mentioned in the docs?

**Comment by pratika2395** [comment]
I'm also having the same issue.. when i try composer install it is showing error -"No command 'composer' found, did you mean:
 Command 'compose' from package 'mime-support' (main)
composer: command not found
"

**Comment by christophrumpel** [comment]
Hey @pratika2395 , you need to have Composer installed. This is a package manager for PHP dependencies. Here instructions for that. Let me know if it helps. https://getcomposer.org/download/

**Comment by pratika2395** [comment]
@christophrumpel, yes sir i got it.. thnkss for your reply. i followed the same link only

**Comment by christophrumpel** [comment]
Perfect 👍
